version: '3.7'
services:
  opensearch:
    #image: opensearchproject/opensearch:2.12.0
    image: opensearchproject/opensearch:2.19.4
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"   # disable HTTPS & auth
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Chinmaymule196@gmail.com"
    ports:
      - 9200:9200
      - 9600:9600   # Performance Analyzer

  opensearch-dashboards:
    #image: opensearchproject/opensearch-dashboards:2.12.0
    image: opensearchproject/opensearch-dashboards:2.19.4
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
